import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const translations = {
  en: {
    // Navbar
    'nav.about': 'About Corp',
    'nav.ventures': 'Our Ventures',
    'nav.tech': 'Livinghub Tech',
    'nav.esgn': 'ESGN',
    'nav.lifestyle': 'Lifestyle',
    'nav.b2b': 'B2B & Gov',
    'nav.values': 'Values',
    'nav.getInTouch': 'Get in Touch',
    'nav.aboutFull': 'About Corporation',
    'nav.venturesFull': 'Our Operating Portfolio',
    'nav.techFull': 'Livinghub Technologies',
    'nav.esgnFull': 'ESGN (E SIM Global Networks)',
    'nav.lifestyleFull': 'Livinghub Lifestyle',
    'nav.b2bFull': 'Corporate & Government Solutions',
    'nav.valuesFull': 'Corporate Values',
    'nav.contactLeader': 'Contact Leadership',

    // Hero
    'hero.badge': 'Multi-Sector Technology, Telecom & Commerce Holding',
    'hero.title1': 'Pioneering',
    'hero.titleSmartLiving': 'Smart Living',
    'hero.titleGlobalTelecom': 'Global Telecom',
    'hero.titleModernLifestyle': '& Enterprise Tech Solutions',
    'hero.description1': 'Livinghub Corporation',
    'hero.description2': 'is the parent enterprise driving forward-looking subsidiaries in smart community automation, borderless digital telecom, modern lifestyle e-commerce, and corporate & government IT solutions.',
    'hero.ctaExplore': 'Explore Operating Entities',
    'hero.ctaAbout': 'About the Holding',
    'hero.treeParent': 'Parent Holding Enterprise',
    'hero.techBadge': 'SaaS & PropTech',
    'hero.techTitle': 'Livinghub Technologies',
    'hero.techDesc': 'Automated smart housing society & building management ERP for treasurers, residents, and security.',
    'hero.techCta': 'Explore Tech Platform',
    'hero.esgnBadge': 'Global Telecom',
    'hero.esgnTitle': 'ESGN (eSIM Global)',
    'hero.esgnDesc': 'Instant worldwide eSIM mobile data and roaming across 150+ countries without physical SIM cards.',
    'hero.esgnCta': 'Discover Global eSIM',
    'hero.lifestyleBadge': 'Upcoming E-Commerce',
    'hero.lifestyleTitle': 'Livinghub Lifestyle',
    'hero.lifestyleDesc': 'Curated everyday lifestyle essentials and smart living products designed for modern homes.',
    'hero.lifestyleCta': 'Preview Brand Vision',
    'hero.b2bBadge': 'Enterprise & B2B Solutions',
    'hero.b2bTitle': 'Corporate & Gov IT Solutions',
    'hero.b2bDesc': 'Software development, IT solutions, technology equipment, and customized supply services for organizations.',
    'hero.b2bCta': 'Explore B2B Solutions',

    // Entities Section
    'entities.badge': 'Core Business Portfolio',
    'entities.title': 'Our Four Operating',
    'entities.titleHighlight': 'Business Pillars',
    'entities.subtitle': 'Livinghub Corporation steers specialized high-growth operating entities across property technology, international telecommunications, digital consumer commerce, and corporate/government IT supply solutions.',

    // Livinghub Tech Entity
    'tech.badge': 'PropTech & SaaS',
    'tech.live': 'Live Enterprise Platform',
    'tech.title': 'Livinghub Technologies',
    'tech.tagline': 'Next-Gen Smart Housing Society & Automated Building Management Platform',
    'tech.desc': 'Transforming manual society accounting and building administration into an automated, 100% transparent digital ecosystem. Designed specifically for treasurers, committee members, and residents to eliminate spreadsheets, billing disputes, and paper receipts.',
    'tech.f1Title': 'Smart Treasurer Dashboard',
    'tech.f1Desc': 'Real-time Cash, Receivables & Payables.',
    'tech.f2Title': 'Automatic Recurring Billing',
    'tech.f2Desc': 'Zero-touch monthly service charges.',
    'tech.f3Title': 'At-Actual Expense Split',
    'tech.f3Desc': 'Common electricity, water & fuel split.',
    'tech.f4Title': 'Automated Police Form',
    'tech.f4Desc': '1-click digital tenant verification generation.',
    'tech.btnVisit': 'Visit livinghub.tech',
    'tech.btnPdf': 'View All 14 PDF Features',
    'tech.stat1Label': 'Treasurer Workload Reduction',
    'tech.stat1Val': '~80% Saved',
    'tech.stat2Label': 'Financial Transparency',
    'tech.stat2Val': '100% Real-Time',
    'tech.stat3Label': 'Billing Dispute Elimination',
    'tech.stat3Val': '1-Click Auto Due Alerts',
    'tech.stat4Label': 'Document Vault',
    'tech.stat4Val': 'Holding Tax, Licenses & Dues',
    'tech.statFooter': 'Deployed Platform',
    'tech.statDemo': 'Explore Live Demo',

    // ESGN Entity
    'esgn.badge': 'International Telecom',
    'esgn.live': 'Live Global Platform',
    'esgn.title': 'ESGN (E SIM Global Networks)',
    'esgn.tagline': 'Borderless High-Speed Travel Data & Digital SIM Connectivity Across 150+ Countries',
    'esgn.desc': 'ESGN provides international travelers, frequent flyers, and global enterprises with instant, prepaid high-speed 4G/5G mobile connectivity. Say goodbye to physical SIM cards, airport queues, and exorbitant roaming fees.',
    'esgn.f1Title': 'Instant QR Activation',
    'esgn.f1Desc': 'Delivered via email in seconds.',
    'esgn.f2Title': '150+ Global Destinations',
    'esgn.f2Desc': 'Seamless local tier-1 network access.',
    'esgn.f3Title': 'Zero Roaming Shock',
    'esgn.f3Desc': 'Transparent prepaid pricing with no hidden fees.',
    'esgn.f4Title': 'Multi-Carrier Reliability',
    'esgn.f4Desc': 'Auto-switches to the strongest local signal.',
    'esgn.btnVisit': 'Visit esimglobalnetworks.com',
    'esgn.stat1Label': 'Global Coverage',
    'esgn.stat1Val': '150+ Countries & Regions',
    'esgn.stat2Label': 'Activation Time',
    'esgn.stat2Val': 'Instant Under 60 Seconds',
    'esgn.stat3Label': 'Hardware Support',
    'esgn.stat3Val': 'iOS, Android & eSIM Tablets',
    'esgn.statFooter': 'Live eSIM Store',
    'esgn.statBrowse': 'Browse Regional Plans',

    // Lifestyle Entity
    'lifestyle.badge': 'Modern E-Commerce',
    'lifestyle.upcoming': 'Upcoming Launch',
    'lifestyle.title': 'Livinghub Lifestyle',
    'lifestyle.tagline': 'Curated E-Commerce & Lifestyle Essentials for Modern Smart Living',
    'lifestyle.desc': 'Livinghub Lifestyle is our upcoming digital retail venture, thoughtfully designed to bring premium lifestyle essentials, home automation accessories, and smart living everyday goods directly to consumer doorsteps.',
    'lifestyle.f1Title': 'Curated Collections',
    'lifestyle.f1Desc': 'Handpicked quality lifestyle products.',
    'lifestyle.f2Title': 'Smart Living Integration',
    'lifestyle.f2Desc': 'Gadgets and accessories for modern homes.',
    'lifestyle.f3Title': 'Seamless Digital Checkout',
    'lifestyle.f3Desc': 'Rapid fulfillment and responsive support.',
    'lifestyle.f4Title': 'Community Synergy',
    'lifestyle.f4Desc': 'Special privileges for LivingHub ecosystem users.',
    'lifestyle.btnVisit': 'Visit livinghublifestyle.com',
    'lifestyle.btnInquiry': 'Partnership & Vendor Inquiry',
    'lifestyle.boxTitle': 'E-Commerce in Active Development',
    'lifestyle.boxDesc': 'Preparing a premier catalog of lifestyle goods, modern living utilities, and smart gadgets.',
    'lifestyle.stat1Label': 'Platform Stage',
    'lifestyle.stat1Val': 'Pre-Launch & Vendor Onboarding',
    'lifestyle.stat2Label': 'Category Scope',
    'lifestyle.stat2Val': 'Smart Living & Lifestyle Essentials',
    'lifestyle.statFooter': 'Reserved Domain',
    'lifestyle.statPreview': 'Visit Preview',

    // B2B & Gov Solutions Entity
    'b2b.badge': 'Enterprise & B2B Solutions',
    'b2b.live': 'Active Enterprise Unit',
    'b2b.title': 'Corporate & Government Enterprise Solutions',
    'b2b.tagline': 'Custom Software Development, IT Infrastructure & Tailored Equipment Supply Services',
    'b2b.desc': 'We provide a comprehensive suite of digital technology services, custom software engineering, turnkey IT solutions, technology hardware equipment, and specialized supply services tailored for corporate enterprises and government organizations.',
    'b2b.f1Title': 'Custom Software Engineering',
    'b2b.f1Desc': 'Tailor-made web, mobile, and enterprise management applications.',
    'b2b.f2Title': 'Turnkey IT Solutions',
    'b2b.f2Desc': 'Cloud architecture, network setup, and digital transformation.',
    'b2b.f3Title': 'Technology Equipment Procurement',
    'b2b.f3Desc': 'Sourcing high-spec hardware, devices, and office tech.',
    'b2b.f4Title': 'Customized Supply Services',
    'b2b.f4Desc': 'Reliable procurement and logistics execution for public & private sectors.',
    'b2b.btnInquire': 'Submit RFP / Procurement Inquiry',
    'b2b.stat1Label': 'Service Portfolio',
    'b2b.stat1Val': 'Software, IT & Supply Solutions',
    'b2b.stat2Label': 'Client Base',
    'b2b.stat2Val': 'Corporate & Government Bodies',
    'b2b.stat3Label': 'Delivery Model',
    'b2b.stat3Val': 'Turnkey & Tailored Procurement',
    'b2b.statFooter': 'Enterprise Solutions Division',
    'b2b.statContact': 'Contact B2B Team',

    // About Section
    'about.badge': 'Corporate Heritage & Vision',
    'about.title': 'About',
    'about.titleHighlight': 'Livinghub Corporation',
    'about.subtitle': 'Livinghub Corporation was established to build, nurture, and scale technology-first enterprises that simplify daily living, remove global borders, and empower communities.',
    'about.missionTitle': 'Our Corporate Mission',
    'about.missionP1': 'To engineer and deliver accessible, robust, and world-class digital platforms across community property management, international roaming telecommunications, high-quality lifestyle retail, and enterprise IT supply services.',
    'about.missionP2': 'We empower housing society administrators with effortless transparency, travelers with instant global connectivity, consumers with curated lifestyle products, and organizations with specialized IT & procurement solutions.',
    'about.visionTitle': 'Our Corporate Vision',
    'about.visionP1': 'To be recognized as a versatile catalyst of innovation, building interconnected digital products and corporate tech services that elevate day-to-day living standards and drive digital transformation.',
    'about.visionP2': 'By leveraging cloud infrastructure, automated billing, seamless eSIM telecommunications, and custom B2B IT solutions, we establish a unified ecosystem for modern living.',
    'about.pillarsHeader': 'How Our Four Ecosystem Pillars Create Synergistic Value',
    'about.p1Title': 'PropTech Infrastructure',
    'about.p1Desc': 'Automating housing communities with financial transparency and smart operations.',
    'about.p2Title': 'Global Roaming Cloud',
    'about.p2Desc': 'Connecting people and smart IoT devices across 150+ countries with zero friction.',
    'about.p3Title': 'Lifestyle Innovation',
    'about.p3Desc': 'Enhancing modern homes with curated premium consumer goods and retail convenience.',
    'about.p4Title': 'Enterprise B2B & Gov',
    'about.p4Desc': 'Empowering organizations with custom software, IT solutions, and tailored tech equipment supply.',

    // Values Section
    'values.badge': 'Guiding Principles',
    'values.title': 'Our Core Corporate',
    'values.titleHighlight': 'Values',
    'values.subtitle': 'The fundamental standards that drive our product development, venture incubation, and customer interactions across all entities.',
    'values.v1Title': 'Technological Excellence',
    'values.v1Desc': 'We build intuitive, robust, and scalable software solutions designed to simplify complex multi-party operations.',
    'values.v2Title': 'Financial Integrity & Transparency',
    'values.v2Desc': 'Whether in society accounting or transparent eSIM rates, we stand firmly for zero hidden costs and total accountability.',
    'values.v3Title': 'Customer-Centric Innovation',
    'values.v3Desc': 'Our products solve real-world daily headaches, from tedious housing committee paperwork to stressful travel data searches.',
    'values.v4Title': 'Sustainable Long-Term Growth',
    'values.v4Desc': 'We build solid partnerships with clients, building associations, telecom operators, and vendors based on mutual trust.',

    // Contact Section
    'contact.badge': 'Connect With Us',
    'contact.title': 'Get in Touch with',
    'contact.titleHighlight': 'Leadership',
    'contact.subtitle': 'Whether you are looking to deploy our Smart Society Management SaaS, partner with ESGN for eSIM distribution, collaborate with Livinghub Lifestyle, or request B2B/Government IT & supply services, we are here to discuss.',
    'contact.emailHeader': 'Corporate & General Email',
    'contact.supportText': 'Tech Platform Support:',
    'contact.venturesHeader': 'Operating Ventures',
    'contact.hqHeader': 'Corporate Headquarters',
    'contact.hqName': 'Livinghub Corporation',
    'contact.hqLoc': 'Dhaka, Bangladesh (Global Digital Operations)',
    'contact.formTitle': 'Send an Inquiry or Proposal',
    'contact.formSubtitle': 'Fill out the form below and our corporate relations team will get back to you within 24 hours.',
    'contact.formTarget': 'Inquiry Target / Entity:',
    'contact.nameLabel': 'Your Full Name *',
    'contact.namePlaceholder': 'e.g. Mahfuzur Rahman',
    'contact.phoneLabel': 'Contact Phone / WhatsApp',
    'contact.phonePlaceholder': 'e.g. +880 1...',
    'contact.emailLabel': 'Email Address *',
    'contact.emailPlaceholder': 'e.g. name@company.com',
    'contact.msgLabel': 'Your Message / Collaboration Proposal *',
    'contact.msgPlaceholder': 'Tell us about your building society, enterprise eSIM requirements, or corporate/government IT inquiry...',
    'contact.btnSubmit': 'Submit Corporate Inquiry',
    'contact.btnSending': 'Sending Inquiry...',
    'contact.successTitle': 'Inquiry Received!',
    'contact.successMsg': 'Thank you for reaching out to Livinghub Corporation regarding',
    'contact.successMsgEnd': 'Our leadership team will review your message and contact you promptly.',
    'contact.btnSendAnother': 'Send Another Inquiry',

    // Footer
    'footer.corpBio': 'Incubating, financing, and scaling innovative technology platforms across smart housing society management, international telecom data, modern lifestyle retail, and corporate/government IT supply solutions.',
    'footer.hq': 'Corporate Headquarters: Dhaka, Bangladesh (Global Digital Operations).',
    'footer.venturesTitle': 'Operating Portfolio',
    'footer.linksTitle': 'Corporate Links',
    'footer.contactTitle': 'Contact Channels',
    'footer.aboutLink': 'About the Corporation',
    'footer.portfolioLink': 'Ventures Portfolio',
    'footer.principlesLink': 'Guiding Principles',
    'footer.inquiriesLink': 'Leadership & Inquiries',
    'footer.backToTop': 'Back to Top',
    'footer.copyright': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
  },
  bn: {
    // Navbar
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.ventures': 'আমাদের সার্ভিসেস',
    'nav.tech': 'লিভিংহাব টেক',
    'nav.esgn': 'ইএসজিএন (ESGN)',
    'nav.lifestyle': 'লাইফস্টাইল',
    'nav.b2b': 'বিটুবি ও গভমেন্ট',
    'nav.values': 'কর্পোরেট ভ্যালুস',
    'nav.getInTouch': 'যোগাযোগ করুন',
    'nav.aboutFull': 'কর্পোরেশন সম্পর্কে',
    'nav.venturesFull': 'আমাদের বিজনেস পোর্টফোলিও',
    'nav.techFull': 'লিভিংহাব টেকনোলজিস',
    'nav.esgnFull': 'ইএসজিএন (গ্লোবাল ই-সিম)',
    'nav.lifestyleFull': 'লিভিংহাব লাইফস্টাইল',
    'nav.b2bFull': 'কর্পোরেট ও গভমেন্ট সলিউশনস',
    'nav.valuesFull': 'কর্পোরেট ভ্যালুস',
    'nav.contactLeader': 'যোগাযোগ করুন',

    // Hero
    'hero.badge': 'টেকনোলজি, টেলিকম ও ডিজিটাল কমার্স গ্রুপ',
    'hero.title1': 'পায়োনিয়ারিং',
    'hero.titleSmartLiving': 'স্মার্ট লিভিং',
    'hero.titleGlobalTelecom': 'গ্লোবাল টেলিকম',
    'hero.titleModernLifestyle': 'ও টেকনোলজি সলিউশনস',
    'hero.description1': 'লিভিংহাব কর্পোরেশন',
    'hero.description2': 'স্মার্ট হাউজিং অটোমেশন, ডিজিটাল রোমিং টেলিকম, লাইফস্টাইল ই-কমার্স এবং কর্পোরেট ও সরকারি আইটি সলিউশন নিয়ে কাজ করা একটি আধুনিক গ্রুপ অফ কোম্পানিজ।',
    'hero.ctaExplore': 'আমাদের সার্ভিসগুলো দেখুন',
    'hero.ctaAbout': 'গ্রুপ সম্পর্কে জানুন',
    'hero.treeParent': 'প্যারেন্ট হোল্ডিং কোম্পানি',
    'hero.techBadge': 'SaaS ও প্রপটেক',
    'hero.techTitle': 'লিভিংহাব টেকনোলজিস',
    'hero.techDesc': 'হাউজিং সোসাইটি ও অ্যাপার্টমেন্ট অটোমেশনের জন্য স্মার্ট ম্যানেজমেন্ট ইআরপি সিস্টেম।',
    'hero.techCta': 'টেক প্ল্যাটফর্ম দেখুন',
    'hero.esgnBadge': 'গ্লোবাল টেলিকম',
    'hero.esgnTitle': 'ইএসজিএন (eSIM Global)',
    'hero.esgnDesc': 'ফিজিক্যাল সিম ছাড়াই ১৫০টিরও বেশি দেশে ইনস্ট্যান্ট হাই-স্পিড ই-সিম ইন্টারনেট।',
    'hero.esgnCta': 'গ্লোবাল ই-সিম দেখুন',
    'hero.lifestyleBadge': 'আপকামিং ই-কমার্স',
    'hero.lifestyleTitle': 'লিভিংহাব লাইফস্টাইল',
    'hero.lifestyleDesc': 'আধুনিক বাসস্থানের জন্য কিউরেটেড এসেনশিয়াল ও স্মার্ট লিভিং প্রোডাক্ট।',
    'hero.lifestyleCta': 'ব্র্যান্ড ভিশন দেখুন',
    'hero.b2bBadge': 'বিটুবি ও গভমেন্ট সলিউশনস',
    'hero.b2bTitle': 'কর্পোরেট ও গভমেন্ট আইটি সার্ভিস',
    'hero.b2bDesc': 'কাস্টম সফটওয়্যার ডেভেলপমেন্ট, আইটি সলিউশন, টেক ইকুইপমেন্ট ও কাস্টমাইজড সাপ্লাই সার্ভিস।',
    'hero.b2bCta': 'বিটুবি সলিউশনস দেখুন',

    // Entities Section
    'entities.badge': 'কোর বিজনেস পোর্টফোলিও',
    'entities.title': 'আমাদের ৪টি প্রধান',
    'entities.titleHighlight': 'বিজনেস সেক্টর',
    'entities.subtitle': 'লিভিংহাব কর্পোরেশন প্রপার্টি টেকনোলজি, আন্তর্জাতিক টেলিকমিউনিকেশন, লাইফস্টাইল ই-কমার্স এবং কর্পোরেট/সরকারি আইটি সলিউশনে কাজ করছে।',

    // Livinghub Tech Entity
    'tech.badge': 'প্রপটেক ও SaaS',
    'tech.live': 'লাইভ এন্টারপ্রাইজ প্ল্যাটফর্ম',
    'tech.title': 'লিভিংহাব টেকনোলজিস',
    'tech.tagline': 'স্মার্ট হাউজিং সোসাইটি ও বিল্ডিং ম্যানেজমেন্ট ইআরপি প্ল্যাটফর্ম',
    'tech.desc': 'ম্যানুয়াল মেম্বারশিপ, বিলিং এবং বিল্ডিং অ্যাডমিনিস্ট্রেশনকে ১০০% ডিজিটাল ও ট্রান্সপারেন্ট সিস্টেমে রূপান্তর করুন। স্প্রেডশিট ও পেপার রিসিট ছাড়াই ট্রেজারার ও কমিটি মেম্বারদের কাজ সহজ করে তোলে।',
    'tech.f1Title': 'স্মার্ট ট্রেজারার ড্যাশবোর্ড',
    'tech.f1Desc': 'রিয়েল-টাইম হিসাব, রিসিভেবলস ও পেয়েবলস।',
    'tech.f2Title': 'অটোমেটিক রিকারিং বিলিং',
    'tech.f2Desc': 'প্রতি মাসের সার্ভিস চার্জের অটো এসএমএস/ইমেইল বিলিং।',
    'tech.f3Title': 'অ্যাট-অ্যাকচুয়াল এক্সপেন্স স্প্লিট',
    'tech.f3Desc': 'বিদ্যুৎ, পানি ও কমন খরচের সঠিক হিসাব বণ্টন।',
    'tech.f4Title': 'অটোমেটেড পুলিশ ফর্ম',
    'tech.f4Desc': '১-ক্লিকে ভাড়াটিয়া ভেরিফিকেশন ফরম তৈরি।',
    'tech.btnVisit': 'livinghub.tech ভিজিট করুন',
    'tech.btnPdf': '১৪টি ফিচারের পিডিএফ দেখুন',
    'tech.stat1Label': 'ট্রেজারারের কাজের চাপ হ্রাস',
    'tech.stat1Val': '~৮০% সময় সাশ্রয়',
    'tech.stat2Label': 'হিসাবের স্বচ্ছতা',
    'tech.stat2Val': '১০-০% রিয়েল-টাইম',
    'tech.stat3Label': 'বিলিং জটিলতা নিরসন',
    'tech.stat3Val': '১-ক্লিক অটো ডিউ অ্যালার্ট',
    'tech.stat4Label': 'ডকুমেন্ট ভল্ট',
    'tech.stat4Val': 'হোল্ডিং ট্যাক্স ও লাইসেন্স ফাইল সেভ',
    'tech.statFooter': 'ডিপ্লয়েড প্ল্যাটফর্ম',
    'tech.statDemo': 'লাইভ ডেমো দেখুন',

    // ESGN Entity
    'esgn.badge': 'ইন্টারন্যাশনাল টেলিকম',
    'esgn.live': 'লাইভ গ্লোবাল প্ল্যাটফর্ম',
    'esgn.title': 'ইএসজিএন (E SIM Global Networks)',
    'esgn.tagline': '১৫০+ দেশে হাই-স্পিড ট্রাভেল ডেটা ও ডিজিটাল ই-সিম কানেক্টিভিটি',
    'esgn.desc': 'বিদেশে ভ্রমণকারী, ব্যবসায়ী ও আন্তর্জাতিক ট্রাভেলারদের জন্য ইনস্ট্যান্ট প্রিপেইড ৪জি/৫জি মোবাইল ডেটা সলিউশন। ফিজিক্যাল সিম কেনা বা এয়ারপোর্টের দীর্ঘ লাইনে দাঁড়ানোর প্রয়োজন নেই।',
    'esgn.f1Title': 'ইনস্ট্যান্ট কিউআর অ্যাক্টিভেশন',
    'esgn.f1Desc': 'ইমেইলের মাধ্যমে কয়েক সেকেন্ডে অ্যাক্টিভেশন।',
    'esgn.f2Title': '১৫০+ দেশে কভারেজ',
    'esgn.f2Desc': 'স্থানীয় এক নম্বর নেটওয়ার্কের উচ্চগতি।',
    'esgn.f3Title': 'হিডেন চার্জ নেই',
    'esgn.f3Desc': 'সাশ্রয়ী প্রিপেইড প্যাকেজ, জিরো রোমিং শক।',
    'esgn.f4Title': 'অটো নেটওয়ার্ক সুইচ',
    'esgn.f4Desc': 'সবচেয়ে শক্তিশালী নেটওয়ার্কে অটোমেটিক কানেক্ট।',
    'esgn.btnVisit': 'esimglobalnetworks.com ভিজিট করুন',
    'esgn.stat1Label': 'গ্লোবাল কভারেজ',
    'esgn.stat1Val': '১৫০+ দেশ ও রিজিয়ন',
    'esgn.stat2Label': 'অ্যাক্টিভেশন সময়',
    'esgn.stat2Val': '৬০ সেকেন্ডের নিচে',
    'esgn.stat3Label': 'ডিভাইস সাপোর্ট',
    'esgn.stat3Val': 'আইফোন, অ্যান্ড্রয়েড ও ই-সিম ট্যাব',
    'esgn.statFooter': 'লাইভ ই-সিম স্টোর',
    'esgn.statBrowse': 'প্যাকেজগুলো দেখুন',

    // Lifestyle Entity
    'lifestyle.badge': 'মডার্ন ই-কমার্স',
    'lifestyle.upcoming': 'আপকামিং লঞ্চ',
    'lifestyle.title': 'লিভিংহাব লাইফস্টাইল',
    'lifestyle.tagline': 'স্মার্ট লিভিং ও লাইফস্টাইল এসেনশিয়ালের প্রিমিয়াম ই-কমার্স',
    'lifestyle.desc': 'লিভিংহাব লাইফস্টাইল আমাদের নতুন ই-কমার্স উদ্যোগ, যা আধুনিক ঘরের জন্য প্রিমিয়াম লাইফস্টাইল প্রোডাক্ট, হোম অটোমেশন গ্যাজেট এবং লাইফস্টাইল আইটেম সরাসরি কাস্টমারের দোরগোড়ায় পৌঁছে দেবে।',
    'lifestyle.f1Title': 'কিউরেটেড কালেকশন',
    'lifestyle.f1Desc': 'মানসম্মত ও আধুনিক লাইফস্টাইল প্রোডাক্ট।',
    'lifestyle.f2Title': 'স্মার্ট হোম গ্যাজেটস',
    'lifestyle.f2Desc': 'আধুনিক ঘরের উপযোগী স্মার্ট অ্যাক্সেসরিজ।',
    'lifestyle.f3Title': 'সহজ ডিজিটাল চেকআউট',
    'lifestyle.f3Desc': 'দ্রুত ডেলিভারি ও রেসপন্সিভ সাপোর্ট।',
    'lifestyle.f4Title': 'কমিউনিটি ডিসকাউন্ট',
    'lifestyle.f4Desc': 'লিভিংহাব ইউজারদের জন্য স্পেশাল অফার।',
    'lifestyle.btnVisit': 'livinghublifestyle.com ভিজিট করুন',
    'lifestyle.btnInquiry': 'ভেন্ডর ও পার্টনারশিপ ইনকোয়ারি',
    'lifestyle.boxTitle': 'ই-কমার্স প্ল্যাটফর্ম তৈরি হচ্ছে',
    'lifestyle.boxDesc': 'আধুনিক ঘরের স্মার্ট গ্যাজেট ও লাইফস্টাইল আইটেমের প্রিমিয়ার ক্যাটালগ প্রস্তুত করা হচ্ছে।',
    'lifestyle.stat1Label': 'বর্তমান অবস্থা',
    'lifestyle.stat1Val': 'প্রি-লঞ্চ ও ভেন্ডর অনবোর্ডিং',
    'lifestyle.stat2Label': 'প্রোডাক্ট ক্যাটাগরি',
    'lifestyle.stat2Val': 'স্মার্ট হোম ও লাইফস্টাইল',
    'lifestyle.statFooter': 'রিজার্ভড ডোমেইন',
    'lifestyle.statPreview': 'প্রিভিউ দেখুন',

    // B2B & Gov Solutions Entity
    'b2b.badge': 'এন্টারপ্রাইজ ও বিটুবি সলিউশনস',
    'b2b.live': 'অ্যাক্টিভ সার্ভিস ডিভিশন',
    'b2b.title': 'কর্পোরেট ও গভর্নমেন্ট এন্টারপ্রাইজ সলিউশনস',
    'b2b.tagline': 'কাস্টম সফটওয়্যার ডেভেলপমেন্ট, আইটি ইনফ্রাস্ট্রাকচার ও টেক ইকুইপমেন্ট সাপ্লাই',
    'b2b.desc': 'আমরা কর্পোরেট এন্টারপ্রাইজ এবং সরকারি প্রতিষ্ঠানের জন্য কাস্টম সফটওয়্যার ডেভেলপমেন্ট, টার্নকি আইটি সলিউশন, টেকনোলজি হার্ডওয়্যার ইকুইপমেন্ট এবং বিশেষায়িত লজিস্টিকস সাপ্লাই সেবা প্রদান করে থাকি।',
    'b2b.f1Title': 'কাস্টম সফটওয়্যার ইঞ্জিনিয়ারিং',
    'b2b.f1Desc': 'প্রয়োজন অনুযায়ী ওয়েব, মোবাইল ও ক্লাউড ইআরপি সিস্টেম।',
    'b2b.f2Title': 'আইটি ইনফ্রাস্ট্রাকচার',
    'b2b.f2Desc': 'নিরাপদ এন্টারপ্রাইজ টেক সেটআপ ও ডিজিটাল ট্রান্সফরমেশন।',
    'b2b.f3Title': 'টেক ইকুইপমেন্ট প্রোকিউরমেন্ট',
    'b2b.f3Desc': 'হাই-পারফরম্যান্স হার্ডওয়্যার, ডিভাইসেস ও অফিস টেকনোলজি।',
    'b2b.f4Title': 'কাস্টমাইজড সাপ্লাই সার্ভিসেস',
    'b2b.f4Desc': 'সরকারি ও সরকারি সংস্থায় নির্ভরযোগ্য প্রোকিউরমেন্ট ও সাপ্লাই।',
    'b2b.btnInquire': 'প্রপোজাল / আরএফপি সাবমিট করুন',
    'b2b.stat1Label': 'সার্ভিস স্কোপ',
    'b2b.stat1Val': 'আইটি, কাস্টম সফটওয়্যার ও প্রোকিউরমেন্ট',
    'b2b.stat2Label': 'টার্গেট ক্লায়েন্ট',
    'b2b.stat2Val': 'কর্পোরেট ও সরকারি সংস্থাসমূহ',
    'b2b.stat3Label': 'ডেলিভারি মডেল',
    'b2b.stat3Val': 'এন্টারপ্রাইজ-গ্রেড সাপোর্ট ও লজিস্টিকস',
    'b2b.statFooter': 'এন্টারপ্রাইজ সলিউশনস ডিভিশন',
    'b2b.statContact': 'বিটুবি টিমের সাথে যোগাযোগ',

    // About Section
    'about.badge': 'আমাদের গল্প ও ভিশন',
    'about.title': 'আমাদের',
    'about.titleHighlight': 'সম্পর্কে',
    'about.subtitle': 'লিভিংহাব কর্পোরেশন প্রতিষ্ঠিত হয়েছে আধুনিক প্রযুক্তি নির্ভর সার্ভিস তৈরির উদ্দেশ্যে, যা দৈনন্দিন জীবনকে সহজ করবে এবং ডিজিটাল সম্ভাবনাকে উন্মোচিত করবে।',
    'about.missionTitle': 'আমাদের মিশন',
    'about.missionP1': 'হাউজিং সোসাইটি ম্যানেজমেন্ট, আন্তর্জাতিক রোমিং টেলিকম, লাইফস্টাইল ই-কমার্স এবং কর্পোরেট আইটি সার্ভিসে সেরা ডিজিটাল অভিজ্ঞতা নিশ্চিত করা।',
    'about.missionP2': 'আমরা বিল্ডিং কমিটিকে দিচ্ছি স্বচ্ছতা, ট্রাভেলারদের দিচ্ছি বিশ্বজুড়ে সহজ ইন্টারনেট, এবং প্রতিষ্ঠানগুলোকে দিচ্ছি বিশ্বস্ত আইটি ও প্রোকিউরমেন্ট সলিউশন।',
    'about.visionTitle': 'আমাদের ভিশন',
    'about.visionP1': 'বাংলাদেশে টেকনোলজি ও ডিজিটাল সার্ভিসের বিশ্বস্ত ব্র্যান্ড হিসেবে নিজেদের গড়ে তোলা এবং উদ্ভাবনী সমাধানের মাধ্যমে গ্রাহকদের জীবনযাত্রার মান উন্নত করা।',
    'about.visionP2': 'ক্লাউড ইনফ্রাস্ট্রাকচার, অটোমেটেড বিলিং, ই-সিম টেলিকম ও বিটুবি সলিউশনের মাধ্যমে একটি সমন্বিত ডিজিটাল ইকোসিস্টেম তৈরি করা।',
    'about.pillarsHeader': 'আমাদের ৪টি প্রধান বিজনেসের সমন্বিত ভ্যালু',
    'about.p1Title': 'প্রপটেক ইনফ্রাস্ট্রাকচার',
    'about.p1Desc': 'স্বচ্ছ হিসাব ও স্মার্ট অটোমেশনের মাধ্যমে হাউজিং সোসাইটি পরিচালনা।',
    'about.p2Title': 'গ্লোবাল রোমিং ক্লাউড',
    'about.p2Desc': '১৫০+ দেশে ফ্রিকশনলেস ডিজিটাল ইন্টারনেট কানেক্টিভিটি।',
    'about.p3Title': 'লাইফস্টাইল ইনোভেশন',
    'about.p3Desc': 'আধুনিক ঘরের উপযোগী কোয়ালিটি প্রোডাক্ট ও ই-কমার্স সুবিধা।',
    'about.p4Title': 'বিটুবি ও গভমেন্ট সলিউশনস',
    'about.p4Desc': 'কাস্টম সফটওয়্যার, আইটি সলিউশন ও টেকনোলজি প্রোকিউরমেন্ট সাপ্লাই।',

    // Values Section
    'values.badge': 'আমাদের মূলনীতি',
    'values.title': 'আমাদের কোর',
    'values.titleHighlight': 'ভ্যালুস',
    'values.subtitle': 'যে নীতিগুলো আমাদের প্রতিদিনের সিদ্ধান্ত ও কাস্টমার সার্ভিসে সবসময় পরিচালিত করে।',
    'values.v1Title': 'প্রযুক্তিগত শ্রেষ্ঠত্ব',
    'values.v1Desc': 'আমরা সহজ, নিখুঁত এবং স্কেলেবল সফটওয়্যার সমাধান তৈরি করি যা জটিল কাজকে সহজ করে।',
    'values.v2Title': 'স্বচ্ছতা ও সততা',
    'values.v2Desc': 'সোসাইটির হিসাব বা ই-সিমের প্যাকেজ—আমরা শূন্য হিডেন চার্জ ও ১০০% জবাবদিহিতায় বিশ্বাসী।',
    'values.v3Title': 'কাস্টমার-সেন্ট্রিক সার্ভিস',
    'values.v3Desc': 'আমাদের প্রতিটি প্রোডাক্ট দৈনন্দিন জীবনের আসল সমস্যা সমাধান করার জন্য তৈরি।',
    'values.v4Title': 'দীর্ঘমেয়াদী পার্টনারশিপ',
    'values.v4Desc': 'ক্লায়েন্ট, বিল্ডিং অ্যাসোসিয়েশন ও পার্টনারদের সাথে পারস্পরিক বিশ্বাসের ভিত্তিতে সম্পর্ক গড়ে তোলা।',

    // Contact Section
    'contact.badge': 'যোগাযোগ',
    'contact.title': 'আমাদের টিমের সাথে',
    'contact.titleHighlight': 'যোগাযোগ করুন',
    'contact.subtitle': 'আপনার হাউজিং সোসাইটিতে সফটওয়্যার ইনস্টল করতে, ESGN ই-সিম পার্টনারশিপ, লাইফস্টাইল কোলাবোরেশন বা কর্পোরেট/সরকারি আইটি প্রোকিউরমেন্টের জন্য আমাদের সাথে কথা বলুন।',
    'contact.emailHeader': 'কর্পোরেট ইমেইল',
    'contact.supportText': 'টেক প্ল্যাটফর্ম সাপোর্ট:',
    'contact.venturesHeader': 'অপারেটিং সার্ভিসেস',
    'contact.hqHeader': 'কর্পোরেট হেডকোয়ার্টার',
    'contact.hqName': 'লিভিংহাব কর্পোরেশন',
    'contact.hqLoc': 'ঢাকা, বাংলাদেশ (গ্লোবাল ডিজিটাল অপারেশনস)',
    'contact.formTitle': 'মেসেজ বা প্রপোজাল পাঠান',
    'contact.formSubtitle': 'নিচের ফর্মটি পূরণ করুন, আমাদের প্রতিনিধি ২৪ ঘণ্টার মধ্যে আপনার সাথে যোগাযোগ করবে।',
    'contact.formTarget': 'যার জন্য ইনকোয়ারি করছেন:',
    'contact.nameLabel': 'আপনার পুরো নাম *',
    'contact.namePlaceholder': 'যেমন: মাহফুজুর রহমান',
    'contact.phoneLabel': 'ফোন নম্বর / হোয়াটসঅ্যাপ',
    'contact.phonePlaceholder': 'যেমন: +880 1...',
    'contact.emailLabel': 'ইমেইল অ্যাড্রেস *',
    'contact.emailPlaceholder': 'যেমন: name@company.com',
    'contact.msgLabel': 'আপনার মেসেজ / প্রপোজাল *',
    'contact.msgPlaceholder': 'আপনার হাউজিং সোসাইটি, ই-সিম রিকোয়ারমেন্ট বা কর্পোরেট আইটি প্রোকিউরমেন্ট সম্পর্কে বলুন...',
    'contact.btnSubmit': 'ইনকোয়ারি সাবমিট করুন',
    'contact.btnSending': 'মেসেজ পাঠানো হচ্ছে...',
    'contact.successTitle': 'ধন্যবাদ! আপনার মেসেজটি আমরা পেয়েছি।',
    'contact.successMsg': 'লিভিংহাব কর্পোরেশনে যোগাযোগ করার জন্য আপনাকে ধন্যবাদ:',
    'contact.successMsgEnd': 'আমাদের টিম দ্রুত আপনার সাথে যোগাযোগ করবে।',
    'contact.btnSendAnother': 'আরেকটি মেসেজ পাঠান',

    // Footer
    'footer.corpBio': 'স্মার্ট হাউজিং ম্যানেজমেন্ট, গ্লোবাল ই-সিম ট্রাভেল ডেটা, লাইফস্টাইল ই-কমার্স এবং কর্পোরেট/সরকারি আইটি সলিউশন সরবরাহকারী একটি উদ্ভাবনী প্রযুক্তি প্রতিষ্ঠান।',
    'footer.hq': 'হেডকোয়ার্টার: ঢাকা, বাংলাদেশ (গ্লোবাল ডিজিটাল অপারেশনস)।',
    'footer.venturesTitle': 'আমাদের সার্ভিসেস',
    'footer.linksTitle': 'গুরুত্বপূর্ণ লিংক',
    'footer.contactTitle': 'যোগাযোগের মাধ্যম',
    'footer.aboutLink': 'গ্রুপ সম্পর্কে',
    'footer.portfolioLink': 'সার্ভিস পোর্টফোলিও',
    'footer.principlesLink': 'আমাদের মূলনীতি',
    'footer.inquiriesLink': 'যোগাযোগ ও মেসেজ',
    'footer.backToTop': 'উপরে যান',
    'footer.copyright': 'সর্বস্বত্ব সংরক্ষিত।',
    'footer.privacy': 'প্রাইভেসি পলিসি',
    'footer.terms': 'টার্মস অফ সার্ভিস',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('livinghub_lang');
    return (saved === 'bn' || saved === 'en') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('livinghub_lang', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const langDict = translations[language];
    return (langDict as Record<string, string>)[key] || (translations.en as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
